python_weather_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("", include("weather.urls")),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import LoginUser, RegisterUser


app_name = 'users'

urlpatterns = [
    path('signin/', LoginUser.as_view(), name='signin'),
    path('signup/', RegisterUser.as_view(), name='signup'),
    path('signout/', LogoutView.as_view(), name='signout'),
]

weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.index, name='index'),
]

users/models.py
from django.db import models

# Create your models here.

weather/models.py
from django.contrib.auth.models import User
from django.db import models


class Location(models.Model):
    name = models.CharField(max_length=255)
    country = models.CharField(max_length=5)
    users_id = models.ManyToManyField(User, related_name='locations')
    lat = models.DecimalField(max_digits=5, decimal_places=2)
    lon = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        unique_together = (('lat', 'lon'),)

    def __str__(self):
        return f"{self.name}: lat: {self.lat}, lon: {self.lon}"

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Username',
                               widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    password = forms.CharField(label='Password',
                                widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Username',
                               widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}))
    password2 = forms.CharField(label='Confirm password',
                                widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2')

users/views.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import LoginUserForm, RegisterUserForm


class LoginUser(LoginView):
    template_name = 'users/signin.html'
    form_class = LoginUserForm

    success_url = reverse_lazy('weather:index')

    extra_context = {
        'title': 'Sign In',
    }


class RegisterUser(CreateView):
    template_name = 'users/signup.html'
    form_class = RegisterUserForm

    success_url = reverse_lazy('users:signin')

    extra_context = {
        'title': 'Sign Up',
    }

weather/views.py
from django.shortcuts import render


def index(request):
    return render(request=request, template_name='weather/index.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-black">
        <div class="container-fluid">
            <a class="navbar-brand text-light" href="{% url 'weather:index' %}">WeatherApp</a>
            <ul class="navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active text-light" href="#">{{ user.username}}</a>
                    </li>
                    <li class="nav-item my-auto">
                        <form action='{% url 'users:signout' %}' method="post">
                            {% csrf_token %}
                            <button type="submit" class='bg-black text-light' style="border:None">Logout</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active text-light" href="{% url 'users:signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active text-light" href="{% url 'users:signin' %}">Sign In</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

users/templates/users/signin.html
{% extends 'base.html' %}

{% block content %}
    <div class="mask d-flex align-items-center h-100 gradient-custom-3 m-5">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-5">Log In</h2>
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-error">{{ form.non_field_errors }}</div>
                                {% for field in form %}
                                    <div class="form-outline mb-4">
                                        <p><label class="form-label" for="{{ field.id_for_label }}">{{field.label}}: </label>{{ field }}</p>
                                        <div class="form-error">{{ field.errors }}</div>
                                    </div>
                                {% endfor %}
                                <div class="d-flex justify-content-center">
                                  <button  type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Sign In</button>
                                </div>
                                <p class="text-center text-muted mt-5 mb-0"><a href="#!"
                                    class="fw-bold text-body"><u>Forgot Password?</u></a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="mask d-flex align-items-center h-100 gradient-custom-3 m-5">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-5">Create an account</h2>
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-error">{{ form.non_field_errors }}</div>
                                {% for field in form %}
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <p><label class="form-label" for="{{ field.id_for_label }}">{{field.label}}: </label>{{ field }}</p>
                                        <div class="form-error">{{ field.errors }}</div>
                                    </div>
                                {% endfor %}
                                <div class="d-flex justify-content-center">
                                  <button  type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Register</button>
                                </div>
                                <p class="text-center text-muted mt-5 mb-0">Have already an account? <a href="#!"
                                    class="fw-bold text-body"><u>Login here</u></a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

weather/templates/weather/index.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}